### PR TITLE
Mac support tweaks

### PR DESCRIPTION
**Pull request by matthewarmand**
Hi @thed24 !

I'm starting to work as a collaborator / maintainer on [`docker-tizonia`](https://github.com/tizonia/docker-tizonia), and as Mac support is a big thing people ask for in Tizonia I'm looking forward to getting your PR merged in as an option for people.

Thanks for all your work and investigation in your fork! I just had a couple tweaks I wanted to suggest. The README changes are largely formatting and content ordering, I left your content pretty much as is. The `docker-tizonia` script changes are just so that the same version of the script will work equally well under Mac and Linux machines.

This might seem a little roundabout, but I had quite a few specific changes in mind and I didn't want to clobber the `master` branch in your fork, so I've opened this PR against your fork so you can check it out (as I myself don't own a Mac). If everything looks good to you we can merge this PR into your fork and then I'll merge your PR in the upstream repo reflecting both our changes.

Please take a glance at this and let me know if you have any issues or feedback.

Thanks!

### CODE REVIEW

**Comment by dominic-codespoti** [comment]
Hey @matthewarmand ! My apologies for not responding recently, I've been using my work Github mainly for a bit now due and as such have totally missed these notifications. I'll give this a test, and if it's all working on Mac, I'll merge it into master for you.

**Comment by dominic-codespoti** [comment]
I've run into an issue regarding Python the following Python modules not being found:
'pafy', 'youtube-dl', 'fuzzywuzzy' 

I believe it's occurred somewhere around the change over to Python 3, as a similar issue surfaced. I'm playing around with a few things currently to fix it, will keep you updated.

**Comment by matthewarmand** [comment]
Yeah those changes got pulled into my changes as well. Which image are you using? Did you use the one you had from before, a fresh `docker pull`, or did you re-run the `build.sh` script to build the image locally?

**Comment by dominic-codespoti** [comment]
It might have been an issue with an old version, it seems to be working now so I will merge it into master.

**Comment by matthewarmand** [comment]
Perfect, thanks! I'll get https://github.com/tizonia/docker-tizonia/pull/8 merged in later on today.

**Pull request merged**
